server:
  port: 8080

spring:
  #  h2:
  #    console:
  #      enabled: true  # H2 Console? ???? ?? (H2 Console? H2 Database? UI? ????? ??)
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/test
    username: sa
    password: sa
  #  datasource:
  #    url: mysql ??
  #    username: ???
  #    password: ????
  #    driver-class-name: com.mysql.cj.jdbc.Driver


  jpa:
    show-sql: false
    generate-ddl: true
    properties:
      hibernate:
        # p6 spy 사용으로 false 처리
        show-sql: false
        format_sql: false
    hibernate:
      ddl-auto: create-drop

logging:
  level:
    org.hibernate: off
    org.hibernate.SQL: off
    org.hibernate.type: off
    com.tutorial: off

decorator:
  datasource:
    p6spy:
      enable-logging: true
      multiline: true

jwt:
  secret: rrowllowkangjungwookkimpangwonrrowllowkangjungwookkimpangwonrrowllowkangjungwookkimpangwonrrowllowkangjungwookkimpangwonrrowllowkangjungwookkimpangwonrrowllowkangjungwookkimpangwon
